---
abstract: 'More tag helpers for your templated and slides'
author:
  - 'Holger Rupprecht <holger.rupprecht@gmx.de>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-MostTagHelpers
provides:
  Mojolicious::Plugin::MostTagHelpers:
    file: lib/Mojolicious/Plugin/MostTagHelpers.pm
    version: 0.02
requires:
  HTML::Tagset: 3.2
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.02
